# Generated by Django 5.1.4 on 2026-06-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_hist_movart_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='descripcion_seo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
